import {
  Landmark,
  Users,
  Wrench,
  Building,
  HeartPulse,
  Ship,
  Shirt,
  Presentation,
  Shield,
  Laptop,
  Trophy,
  ArrowRightLeft,
  TrendingDown,
  Banknote,
  Briefcase,
  BookUser,
  Medal,
  Handshake,
  GraduationCap,
  Ticket,
  Beer,
  Tv,
  Film,
  PiggyBank
} from 'lucide-react';

export const flowSteps = [
  { id: 'basic-info', title: 'Informações Básicas' },
  { id: 'revenues', title: 'Receitas' },
  { id: 'personnel-costs', title: 'Custos com Pessoal' },
  { id: 'operational-costs', title: 'Custos Operacionais' },
  { id: 'finalize', title: 'Finalização' },
];

export const revenueCategories = [
  {
    key: 'fieldRental',
    name: 'Aluguel de Campos',
    icon: Building,
    color: 'text-emerald-600',
    fields: [
      { key: 'regularRentals', label: 'Aluguéis Regulares', placeholder: 'Ex: 25.000' },
      { key: 'tournaments', label: 'Torneios e Campeonatos', placeholder: 'Ex: 8.000' },
      { key: 'corporateEvents', label: 'Eventos Corporativos', placeholder: 'Ex: 5.000' },
      { key: 'trainingRentals', label: 'Aluguel para Treinamentos', placeholder: 'Ex: 3.000' },
      { key: 'maintenanceFees', label: 'Taxas de Manutenção (Inclusas)', placeholder: 'Ex: 1.000' },
      { key: 'seasonalAdjustment', label: 'Ajuste Sazonal (%)', placeholder: 'Ex: 10' },
    ],
  },
  {
    key: 'membership',
    name: 'Sócios e Membros',
    icon: Users,
    color: 'text-blue-600',
    fields: [
      { key: 'monthlyFees', label: 'Mensalidades', placeholder: 'Ex: 50.000' },
      { key: 'annualFees', label: 'Anuidades', placeholder: 'Ex: 100.000' },
      { key: 'initiationFees', label: 'Taxas de Adesão (Jóia)', placeholder: 'Ex: 20.000' },
      { key: 'familyPackages', label: 'Pacotes Familiares', placeholder: 'Ex: 15.000' },
      { key: 'corporateMembers', label: 'Sócios Corporativos', placeholder: 'Ex: 30.000' },
      { key: 'vipMemberships', label: 'Planos VIP/Premium', placeholder: 'Ex: 25.000' },
      { key: 'loyaltyPrograms', label: 'Programas de Fidelidade', placeholder: 'Ex: 5.000' },
    ],
  },
  {
    key: 'sponsorship',
    name: 'Patrocínios',
    icon: Handshake,
    color: 'text-purple-600',
    fields: [
        { key: 'mainSponsor', label: 'Patrocinador Master', placeholder: 'Ex: 1.000.000' },
        { key: 'jerseySponsors', label: 'Patrocínios de Uniforme', placeholder: 'Ex: 500.000' },
        { key: 'facilityNaming', label: 'Naming Rights (Estádio/CT)', placeholder: 'Ex: 2.000.000' },
        { key: 'equipmentSponsors', label: 'Fornecedor de Material Esportivo', placeholder: 'Ex: 300.000' },
        { key: 'eventSponsors', label: 'Patrocínio de Eventos', placeholder: 'Ex: 100.000' },
        { key: 'digitalSponsors', label: 'Patrocínios Digitais', placeholder: 'Ex: 150.000' },
        { key: 'stadiumSponsors', label: 'Placas de Publicidade/Estádio', placeholder: 'Ex: 200.000' },
        { key: 'broadcastSponsors', label: 'Patrocínio de Transmissões', placeholder: 'Ex: 250.000' },
    ],
  },
  {
    key: 'soccerSchool',
    name: 'Escola de Futebol',
    icon: GraduationCap,
    color: 'text-cyan-600',
    fields: [
      { key: 'monthlyTuition', label: 'Mensalidades', placeholder: 'Ex: 40.000' },
      { key: 'enrollmentFees', label: 'Taxas de Matrícula', placeholder: 'Ex: 10.000' },
      { key: 'camps', label: 'Clínicas e Acampamentos (Camps)', placeholder: 'Ex: 15.000' },
      { key: 'privateClasses', label: 'Aulas Particulares', placeholder: 'Ex: 5.000' },
      { key: 'tournaments', label: 'Inscrição em Torneios', placeholder: 'Ex: 7.000' },
      { key: 'specialPrograms', label: 'Programas Especiais', placeholder: 'Ex: 8.000' },
      { key: 'equipment', label: 'Venda de Uniformes/Equipamentos', placeholder: 'Ex: 12.000' },
    ],
  },
  {
    key: 'events',
    name: 'Realização de Eventos',
    icon: Medal,
    color: 'text-rose-600',
    fields: [
      { key: 'corporateEvents', label: 'Eventos Corporativos', placeholder: 'Ex: 20.000' },
      { key: 'privateParties', label: 'Festas Particulares', placeholder: 'Ex: 10.000' },
      { key: 'tournaments', label: 'Organização de Torneios', placeholder: 'Ex: 30.000' },
      { key: 'camps', label: 'Organização de Acampamentos', placeholder: 'Ex: 25.000' },
      { key: 'weddings', label: 'Casamentos e Formaturas', placeholder: 'Ex: 15.000' },
      { key: 'conferences', label: 'Conferências e Workshops', placeholder: 'Ex: 18.000' },
      { key: 'shows', label: 'Shows e Espetáculos', placeholder: 'Ex: 50.000' },
      { key: 'other', label: 'Outros Eventos', placeholder: 'Ex: 5.000' },
    ],
  },
  {
    key: 'merchandise',
    name: 'Merchandise e Varejo',
    icon: Shirt,
    color: 'text-indigo-600',
    fields: [
      { key: 'jerseys', label: 'Venda de Camisas', placeholder: 'Ex: 100.000' },
      { key: 'accessories', label: 'Acessórios (Bonés, Cachecóis)', placeholder: 'Ex: 30.000' },
      { key: 'souvenirs', label: 'Lembranças e Souvenirs', placeholder: 'Ex: 20.000' },
      { key: 'equipment', label: 'Equipamentos (Bolas, Chuteiras)', placeholder: 'Ex: 15.000' },
      { key: 'collectibles', label: 'Itens de Colecionador', placeholder: 'Ex: 10.000' },
      { key: 'customProducts', label: 'Produtos Personalizados', placeholder: 'Ex: 5.000' },
    ],
  },
  {
    key: 'foodBeverage',
    name: 'Alimentos e Bebidas',
    icon: Beer,
    color: 'text-orange-600',
    fields: [
      { key: 'restaurant', label: 'Restaurante e Lanchonete', placeholder: 'Ex: 60.000' },
      { key: 'bar', label: 'Bar e Bebidas', placeholder: 'Ex: 40.000' },
      { key: 'catering', label: 'Serviços de Catering', placeholder: 'Ex: 20.000' },
      { key: 'vending', label: 'Máquinas de Venda Automática', placeholder: 'Ex: 5.000' },
      { key: 'events', label: 'Vendas em Dias de Evento', placeholder: 'Ex: 25.000' },
      { key: 'delivery', label: 'Delivery', placeholder: 'Ex: 10.000' },
    ],
  },
  {
    key: 'broadcastRights',
    name: 'Direitos de Transmissão',
    icon: Tv,
    color: 'text-pink-600',
    fields: [
      { key: 'tvRights', label: 'Direitos de TV (Local/Nacional)', placeholder: 'Ex: 5.000.000' },
      { key: 'streamingRights', label: 'Direitos de Streaming', placeholder: 'Ex: 1.000.000' },
      { key: 'radioRights', label: 'Direitos de Rádio', placeholder: 'Ex: 200.000' },
      { key: 'internationalRights', label: 'Direitos Internacionais', placeholder: 'Ex: 2.000.000' },
      { key: 'digitalRights', label: 'Direitos para Conteúdo Digital', placeholder: 'Ex: 500.000' },
      { key: 'archiveRights', label: 'Direitos sobre Arquivo (Jogos Antigos)', placeholder: 'Ex: 100.000' },
    ],
  },
  {
    key: 'playerTransfers',
    name: 'Transferências de Jogadores (Receitas)',
    icon: ArrowRightLeft,
    color: 'text-teal-600',
    fields: [
      { key: 'transferFees', label: 'Taxas de Transferência (Vendas)', placeholder: 'Ex: 10.000.000' },
      { key: 'loanFees', label: 'Taxas de Empréstimo (Jogadores Cedidos)', placeholder: 'Ex: 500.000' },
      { key: 'solidarityMechanism', label: 'Mecanismo de Solidariedade da FIFA', placeholder: 'Ex: 200.000' },
      { key: 'trainingCompensation', label: 'Compensação por Formação', placeholder: 'Ex: 300.000' },
      { key: 'agentCommissions', label: 'Comissões (Recebidas)', placeholder: 'Ex: 50.000' },
      { key: 'contractExtensions', label: 'Luvas por Extensão de Contrato (Recebidas)', placeholder: 'Ex: 100.000' },
    ],
  },
  {
    key: 'ticketing',
    name: 'Bilheteria',
    icon: Ticket,
    color: 'text-amber-600',
    fields: [
      { key: 'seasonTickets', label: 'Ingressos de Temporada (Season Tickets)', placeholder: 'Ex: 1.000.000' },
      { key: 'singleGameTickets', label: 'Ingressos de Jogos Avulsos', placeholder: 'Ex: 500.000' },
      { key: 'vipBoxes', label: 'Camarotes e Áreas VIP', placeholder: 'Ex: 300.000' },
      { key: 'groupSales', label: 'Vendas para Grupos', placeholder: 'Ex: 100.000' },
      { key: 'studentDiscounts', label: 'Descontos para Estudantes', placeholder: 'Ex: 50.000' },
      { key: 'corporatePackages', label: 'Pacotes Corporativos', placeholder: 'Ex: 200.000' },
    ],
  },
  {
    key: 'socialClub',
    name: 'Clube Social',
    icon: BookUser,
    color: 'text-lime-600',
    fields: [
      { key: 'membershipFees', label: 'Mensalidades de Sócios', placeholder: 'Ex: 75.000' },
      { key: 'socialEvents', label: 'Eventos Sociais', placeholder: 'Ex: 25.000' },
      { key: 'facilityRental', label: 'Aluguel de Salões/Churrasqueiras', placeholder: 'Ex: 30.000' },
      { key: 'restaurantRevenue', label: 'Receita do Restaurante do Clube', placeholder: 'Ex: 50.000' },
      { key: 'otherServices', label: 'Outros Serviços (Academias, Piscinas)', placeholder: 'Ex: 40.000' },
    ],
  },
  {
    key: 'prizesMoney',
    name: 'Premiações',
    icon: Trophy,
    color: 'text-yellow-500',
    fields: [
      { key: 'championshipPrizes', label: 'Prêmios por Campeonatos', placeholder: 'Ex: 2.000.000' },
      { key: 'cupPrizes', label: 'Prêmios por Copas', placeholder: 'Ex: 1.000.000' },
      { key: 'performanceBonuses', label: 'Bônus por Performance (Liga)', placeholder: 'Ex: 500.000' },
      { key: 'federationIncentives', label: 'Incentivos da Federação', placeholder: 'Ex: 100.000' },
    ],
  },
  {
    key: 'licensing',
    name: 'Licenciamento e Royalties',
    icon: Shield,
    color: 'text-gray-500',
    fields: [
      { key: 'brandLicensing', label: 'Licenciamento de Marca para Produtos', placeholder: 'Ex: 150.000' },
      { key: 'imageRights', label: 'Direitos de Imagem Coletivos', placeholder: 'Ex: 200.000' },
      { key: 'logoUsage', label: 'Uso de Logo em Mídia', placeholder: 'Ex: 50.000' },
      { key: 'merchandiseLicensing', label: 'Licenciamento para Merchandise', placeholder: 'Ex: 100.000' },
    ],
  },
  {
    key: 'digitalRevenues',
    name: 'Receitas Digitais',
    icon: Film,
    color: 'text-red-500',
    fields: [
      { key: 'websiteAds', label: 'Publicidade em Website/App', placeholder: 'Ex: 30.000' },
      { key: 'socialMediaSponsors', label: 'Monetização de Redes Sociais', placeholder: 'Ex: 50.000' },
      { key: 'onlineStore', label: 'Vendas da Loja Online (E-commerce)', placeholder: 'Ex: 80.000' },
      { key: 'subscription', label: 'Conteúdo por Assinatura (Club TV+)', placeholder: 'Ex: 100.000' },
      { key: 'digitalContent', label: 'Venda de Conteúdo Digital (NFTs)', placeholder: 'Ex: 20.000' },
    ],
  },
  {
    key: 'investments',
    name: 'Investimentos e Receitas Financeiras',
    icon: PiggyBank,
    color: 'text-green-700',
    fields: [
      { key: 'bankInterest', label: 'Juros de Aplicações Bancárias', placeholder: 'Ex: 10.000' },
      { key: 'stockDividends', label: 'Dividendos de Ações', placeholder: 'Ex: 5.000' },
      { key: 'realEstate', label: 'Receitas Imobiliárias', placeholder: 'Ex: 20.000' },
      { key: 'otherInvestments', label: 'Outros Investimentos', placeholder: 'Ex: 15.000' },
    ],
  },
];

export const personnelCategories = [
  {
    key: 'technicalStaff',
    name: 'Comissão Técnica',
    icon: Users,
    color: 'text-blue-600',
    fields: [
      { key: 'headCoach', label: 'Técnico Principal', placeholder: 'Ex: 50.000' },
      { key: 'assistantCoaches', label: 'Auxiliares Técnicos', placeholder: 'Ex: 30.000' },
      { key: 'physicalTrainer', label: 'Preparador Físico', placeholder: 'Ex: 20.000' },
      { key: 'goalkeeper', label: 'Treinador de Goleiros', placeholder: 'Ex: 15.000' },
      { key: 'analyst', label: 'Analista de Desempenho', placeholder: 'Ex: 12.000' },
      { key: 'scout', label: 'Olheiro (Scout)', placeholder: 'Ex: 10.000' },
      { key: 'coordinator', label: 'Coordenador Técnico', placeholder: 'Ex: 25.000' },
      { key: 'interpreter', label: 'Intérprete', placeholder: 'Ex: 5.000' },
      { key: 'other', label: 'Outros (Comissão Técnica)', placeholder: 'Ex: 3.000' },
    ],
  },
  {
    key: 'players',
    name: 'Jogadores',
    icon: Users,
    color: 'text-green-600',
    fields: [
      { key: 'salaries', label: 'Salários (CLT)', placeholder: 'Ex: 1.000.000' },
      { key: 'bonuses', label: 'Bônus e Premiações (Bicho)', placeholder: 'Ex: 200.000' },
      { key: 'benefits', label: 'Benefícios (Moradia, Transporte)', placeholder: 'Ex: 50.000' },
      { key: 'laborCharges', label: 'Encargos Trabalhistas (FGTS, INSS)', placeholder: 'Ex: 300.000' },
      { key: 'medicalInsurance', label: 'Plano de Saúde', placeholder: 'Ex: 40.000' },
      { key: 'imageRights', label: 'Direitos de Imagem', placeholder: 'Ex: 500.000' },
      { key: 'performanceBonuses', label: 'Bônus por Performance Contratual', placeholder: 'Ex: 100.000' },
      { key: 'loyaltyBonuses', label: 'Luvas (Contratação/Renovação)', placeholder: 'Ex: 150.000' },
      { key: 'thirteenthSalary', label: '13º Salário', placeholder: 'Ex: 83.000' },
      { key: 'vacation', label: 'Férias', placeholder: 'Ex: 83.000' },
    ],
  },
  {
    key: 'administrativeStaff',
    name: 'Staff Administrativo',
    icon: Briefcase,
    color: 'text-purple-600',
    fields: [
      { key: 'management', label: 'Diretoria e Gerência', placeholder: 'Ex: 100.000' },
      { key: 'accounting', label: 'Contabilidade', placeholder: 'Ex: 20.000' },
      { key: 'legal', label: 'Departamento Jurídico', placeholder: 'Ex: 25.000' },
      { key: 'hr', label: 'Recursos Humanos', placeholder: 'Ex: 15.000' },
      { key: 'marketing', label: 'Marketing', placeholder: 'Ex: 30.000' },
      { key: 'communication', label: 'Comunicação e Imprensa', placeholder: 'Ex: 18.000' },
      { key: 'finance', label: 'Financeiro', placeholder: 'Ex: 22.000' },
      { key: 'operations', label: 'Operações', placeholder: 'Ex: 28.000' },
      { key: 'commercial', label: 'Comercial', placeholder: 'Ex: 35.000' },
      { key: 'other', label: 'Outros (Administrativo)', placeholder: 'Ex: 5.000' },
    ],
  },
  {
    key: 'supportStaff',
    name: 'Staff de Apoio',
    icon: Wrench,
    color: 'text-orange-600',
    fields: [
      { key: 'security', label: 'Segurança', placeholder: 'Ex: 40.000' },
      { key: 'cleaning', label: 'Limpeza', placeholder: 'Ex: 30.000' },
      { key: 'maintenance', label: 'Manutenção Geral', placeholder: 'Ex: 25.000' },
      { key: 'reception', label: 'Recepção', placeholder: 'Ex: 10.000' },
      { key: 'kitManager', label: 'Rouparia', placeholder: 'Ex: 8.000' },
      { key: 'groundsKeeper', label: 'Manutenção do Gramado', placeholder: 'Ex: 12.000' },
      { key: 'driver', label: 'Motoristas', placeholder: 'Ex: 15.000' },
      { key: 'cook', label: 'Cozinheiros e Nutricionistas', placeholder: 'Ex: 20.000' },
      { key: 'other', label: 'Outros (Apoio)', placeholder: 'Ex: 5.000' },
    ],
  },
  {
    key: 'medicalStaff',
    name: 'Departamento Médico (Salários)',
    icon: HeartPulse,
    color: 'text-red-600',
    fields: [
      { key: 'teamDoctor', label: 'Médico do Time', placeholder: 'Ex: 30.000' },
      { key: 'physiotherapist', label: 'Fisioterapeuta', placeholder: 'Ex: 25.000' },
      { key: 'psychologist', label: 'Psicólogo', placeholder: 'Ex: 15.000' },
      { key: 'nutritionist', label: 'Nutricionista', placeholder: 'Ex: 15.000' },
      { key: 'nurse', label: 'Enfermeiro', placeholder: 'Ex: 10.000' },
      { key: 'masseur', label: 'Massagista', placeholder: 'Ex: 8.000' },
    ],
  },
];

export const operationalCategories = [
  {
    key: 'facilities',
    name: 'Instalações e Infraestrutura',
    icon: Building,
    color: 'text-yellow-600',
    fields: [
      { key: 'rent', label: 'Aluguel (Escritório/CT/Estádio)', placeholder: 'Ex: 50.000' },
      { key: 'propertyTax', label: 'IPTU e Taxas Imobiliárias', placeholder: 'Ex: 10.000' },
      { key: 'condominiumFees', label: 'Taxas de Condomínio', placeholder: 'Ex: 5.000' },
      { key: 'fieldMaintenance', label: 'Manutenção do Gramado (Produtos)', placeholder: 'Ex: 15.000' },
      { key: 'buildingMaintenance', label: 'Manutenção Predial', placeholder: 'Ex: 20.000' },
      { key: 'landscaping', label: 'Paisagismo', placeholder: 'Ex: 5.000' },
      { key: 'stadiumMaintenance', label: 'Manutenção do Estádio', placeholder: 'Ex: 30.000' },
      { key: 'securitySystems', label: 'Sistemas de Segurança (Manutenção)', placeholder: 'Ex: 8.000' },
      { key: 'cleaningServices', label: 'Serviços de Limpeza Terceirizados', placeholder: 'Ex: 12.000' },
      { key: 'wasteManagement', label: 'Gestão de Resíduos', placeholder: 'Ex: 4.000' },
    ],
  },
  {
    key: 'utilities',
    name: 'Utilidades',
    icon: Wrench,
    color: 'text-cyan-600',
    fields: [
      { key: 'electricity', label: 'Eletricidade', placeholder: 'Ex: 40.000' },
      { key: 'water', label: 'Água e Esgoto', placeholder: 'Ex: 15.000' },
      { key: 'gas', label: 'Gás', placeholder: 'Ex: 5.000' },
      { key: 'internet', label: 'Internet', placeholder: 'Ex: 10.000' },
      { key: 'phone', label: 'Telefonia', placeholder: 'Ex: 8.000' },
      { key: 'cable', label: 'TV a Cabo', placeholder: 'Ex: 3.000' },
      { key: 'heatingCooling', label: 'Climatização (Aquecimento/Ar Cond.)', placeholder: 'Ex: 12.000' },
    ],
  },
  {
    key: 'medical',
    name: 'Departamento Médico (Custos)',
    icon: HeartPulse,
    color: 'text-red-500',
    fields: [
      { key: 'supplements', label: 'Suplementos e Medicamentos', placeholder: 'Ex: 20.000' },
      { key: 'medicalExams', label: 'Exames Médicos e Laboratoriais', placeholder: 'Ex: 15.000' },
      { key: 'treatments', label: 'Tratamentos e Terapias', placeholder: 'Ex: 25.000' },
      { key: 'surgeries', label: 'Cirurgias', placeholder: 'Ex: 50.000' },
      { key: 'emergencyMedical', label: 'Atendimento Médico Emergencial', placeholder: 'Ex: 10.000' },
      { key: 'preventiveMedicine', label: 'Medicina Preventiva', placeholder: 'Ex: 8.000' },
      { key: 'rehabilitation', label: 'Reabilitação', placeholder: 'Ex: 12.000' },
      { key: 'medicalEquipment', label: 'Equipamentos Médicos (Compra/Aluguel)', placeholder: 'Ex: 18.000' },
    ],
  },
  {
    key: 'transportation',
    name: 'Transporte e Viagens',
    icon: Ship,
    color: 'text-blue-700',
    fields: [
      { key: 'teamTransport', label: 'Transporte da Equipe (Ônibus)', placeholder: 'Ex: 30.000' },
      { key: 'accommodation', label: 'Hospedagem em Viagens', placeholder: 'Ex: 50.000' },
      { key: 'meals', label: 'Alimentação em Viagens', placeholder: 'Ex: 40.000' },
      { key: 'fuel', label: 'Combustível', placeholder: 'Ex: 15.000' },
      { key: 'vehicleMaintenance', label: 'Manutenção de Veículos', placeholder: 'Ex: 10.000' },
      { key: 'airTravel', label: 'Viagens Aéreas', placeholder: 'Ex: 100.000' },
      { key: 'localTransport', label: 'Transporte Local (Staff/Jogadores)', placeholder: 'Ex: 8.000' },
      { key: 'carRental', label: 'Aluguel de Carros', placeholder: 'Ex: 5.000' },
      { key: 'parking', label: 'Estacionamento', placeholder: 'Ex: 3.000' },
    ],
  },
  {
    key: 'equipment',
    name: 'Equipamentos e Material Esportivo',
    icon: Shirt,
    color: 'text-green-500',
    fields: [
      { key: 'sportingGoods', label: 'Material Esportivo (Chuteiras, etc)', placeholder: 'Ex: 40.000' },
      { key: 'uniforms', label: 'Uniformes de Jogo e Treino', placeholder: 'Ex: 60.000' },
      { key: 'trainingEquipment', label: 'Equipamentos de Treino (Cones, etc)', placeholder: 'Ex: 20.000' },
      { key: 'fieldEquipment', label: 'Equipamentos de Campo (Redes, etc)', placeholder: 'Ex: 10.000' },
      { key: 'safety', label: 'Material de Segurança', placeholder: 'Ex: 5.000' },
      { key: 'balls', label: 'Bolas', placeholder: 'Ex: 15.000' },
      { key: 'goals', label: 'Traves e Balizas', placeholder: 'Ex: 8.000' },
      { key: 'officeEquipment', label: 'Equipamentos de Escritório', placeholder: 'Ex: 12.000' },
      { key: 'vehicles', label: 'Aquisição/Leasing de Veículos', placeholder: 'Ex: 25.000' },
    ],
  },
  {
    key: 'marketing',
    name: 'Marketing e Comunicação',
    icon: Presentation,
    color: 'text-purple-500',
    fields: [
      { key: 'advertising', label: 'Publicidade e Propaganda', placeholder: 'Ex: 50.000' },
      { key: 'digitalMarketing', label: 'Marketing Digital (Ads, SEO)', placeholder: 'Ex: 30.000' },
      { key: 'events', label: 'Promoção de Eventos', placeholder: 'Ex: 20.000' },
      { key: 'materials', label: 'Materiais Gráficos e Brindes', placeholder: 'Ex: 15.000' },
      { key: 'sponsorshipActivation', label: 'Ativação de Patrocínios', placeholder: 'Ex: 25.000' },
      { key: 'publicRelations', label: 'Relações Públicas e Assessoria', placeholder: 'Ex: 18.000' },
      { key: 'socialMedia', label: 'Ferramentas de Mídias Sociais', placeholder: 'Ex: 10.000' },
      { key: 'websiteMaintenance', label: 'Manutenção do Website/App', placeholder: 'Ex: 8.000' },
      { key: 'photography', label: 'Fotografia', placeholder: 'Ex: 5.000' },
      { key: 'videoProduction', label: 'Produção de Vídeo', placeholder: 'Ex: 12.000' },
    ],
  },
  {
    key: 'administrative',
    name: 'Administrativo',
    icon: Briefcase,
    color: 'text-indigo-500',
    fields: [
      { key: 'accounting', label: 'Serviços de Contabilidade', placeholder: 'Ex: 15.000' },
      { key: 'legal', label: 'Honorários Advocatícios', placeholder: 'Ex: 20.000' },
      { key: 'consulting', label: 'Consultorias', placeholder: 'Ex: 18.000' },
      { key: 'banking', label: 'Taxas Bancárias', placeholder: 'Ex: 5.000' },
      { key: 'office', label: 'Material de Escritório', placeholder: 'Ex: 8.000' },
      { key: 'travel', label: 'Viagens Administrativas', placeholder: 'Ex: 10.000' },
      { key: 'subscription', label: 'Assinaturas de Softwares/Publicações', placeholder: 'Ex: 6.000' },
      { key: 'software', label: 'Licenças de Software', placeholder: 'Ex: 12.000' },
      { key: 'audit', label: 'Auditoria', placeholder: 'Ex: 25.000' },
      { key: 'notary', label: 'Cartório e Despesas Notariais', placeholder: 'Ex: 3.000' },
    ],
  },
  {
    key: 'insurance',
    name: 'Seguros',
    icon: Shield,
    color: 'text-gray-600',
    fields: [
      { key: 'liability', label: 'Seguro de Responsabilidade Civil', placeholder: 'Ex: 20.000' },
      { key: 'property', label: 'Seguro Patrimonial', placeholder: 'Ex: 15.000' },
      { key: 'players', label: 'Seguro de Vida/Acidentes para Jogadores', placeholder: 'Ex: 50.000' },
      { key: 'equipment', label: 'Seguro de Equipamentos', placeholder: 'Ex: 10.000' },
      { key: 'vehicles', label: 'Seguro de Veículos', placeholder: 'Ex: 12.000' },
      { key: 'directors', label: 'Seguro D&O (Diretores)', placeholder: 'Ex: 18.000' },
      { key: 'publicLiability', label: 'Seguro de Responsabilidade Pública', placeholder: 'Ex: 22.000' },
      { key: 'cyber', label: 'Seguro Cibernético', placeholder: 'Ex: 15.000' },
    ],
  },
  {
    key: 'regulatory',
    name: 'Regulatório e Federação',
    icon: Landmark,
    color: 'text-slate-600',
    fields: [
      { key: 'licenses', label: 'Licenças e Alvarás', placeholder: 'Ex: 10.000' },
      { key: 'federationFees', label: 'Taxas da Federação/Confederação', placeholder: 'Ex: 30.000' },
      { key: 'certifications', label: 'Certificações', placeholder: 'Ex: 8.000' },
      { key: 'inspections', label: 'Inspeções e Vistorias', placeholder: 'Ex: 5.000' },
      { key: 'arbitrageFees', label: 'Taxas de Arbitragem', placeholder: 'Ex: 40.000' },
      { key: 'registrations', label: 'Registro de Jogadores/Contratos', placeholder: 'Ex: 15.000' },
      { key: 'fines', label: 'Multas e Penalidades', placeholder: 'Ex: 20.000' },
      { key: 'legalFees', label: 'Custas Judiciais (Regulatório)', placeholder: 'Ex: 12.000' },
    ],
  },
  {
    key: 'technology',
    name: 'Tecnologia',
    icon: Laptop,
    color: 'text-sky-500',
    fields: [
      { key: 'software', label: 'Licenças de Software (Análise, Gestão)', placeholder: 'Ex: 25.000' },
      { key: 'hardware', label: 'Hardware (Computadores, Servidores)', placeholder: 'Ex: 15.000' },
      { key: 'telecommunications', label: 'Telecomunicações', placeholder: 'Ex: 10.000' },
      { key: 'support', label: 'Suporte Técnico Terceirizado', placeholder: 'Ex: 8.000' },
      { key: 'cloudServices', label: 'Serviços em Nuvem (AWS, Azure)', placeholder: 'Ex: 12.000' },
      { key: 'backup', label: 'Backup e Recuperação de Dados', placeholder: 'Ex: 5.000' },
      { key: 'cybersecurity', label: 'Cibersegurança', placeholder: 'Ex: 18.000' },
      { key: 'streamingPlatform', label: 'Plataforma de Streaming (Custos)', placeholder: 'Ex: 22.000' },
    ],
  },
  {
    key: 'competitions',
    name: 'Competições e Jogos',
    icon: Trophy,
    color: 'text-yellow-500',
    fields: [
      { key: 'registrationFees', label: 'Taxas de Inscrição em Competições', placeholder: 'Ex: 20.000' },
      { key: 'travelExpenses', label: 'Despesas de Viagem (Jogos)', placeholder: 'Ex: 100.000' },
      { key: 'accommodation', label: 'Hospedagem (Jogos)', placeholder: 'Ex: 80.000' },
      { key: 'meals', label: 'Alimentação (Jogos)', placeholder: 'Ex: 60.000' },
      { key: 'arbitrageFees', label: 'Taxas de Arbitragem (Jogos)', placeholder: 'Ex: 50.000' },
      { key: 'medicalSupport', label: 'Apoio Médico em Jogos', placeholder: 'Ex: 10.000' },
      { key: 'security', label: 'Segurança em Dias de Jogo', placeholder: 'Ex: 30.000' },
      { key: 'organization', label: 'Organização de Jogos em Casa', placeholder: 'Ex: 40.000' },
    ],
  },
  {
    key: 'transfers',
    name: 'Transferências e Contratações (Custos)',
    icon: ArrowRightLeft,
    color: 'text-teal-500',
    fields: [
      { key: 'agentCommissions', label: 'Comissões de Agentes', placeholder: 'Ex: 500.000' },
      { key: 'transferFees', label: 'Taxas de Transferência (Compras)', placeholder: 'Ex: 5.000.000' },
      { key: 'loanFees', label: 'Taxas de Empréstimo (Jogadores Contratados)', placeholder: 'Ex: 200.000' },
      { key: 'scoutingExpenses', label: 'Despesas com Scouting/Observação', placeholder: 'Ex: 100.000' },
      { key: 'medicalExams', label: 'Exames Médicos de Contratação', placeholder: 'Ex: 20.000' },
      { key: 'registrationFees', label: 'Taxas de Registro de Contrato', placeholder: 'Ex: 15.000' },
      { key: 'contractNegotiation', label: 'Custos de Negociação de Contrato', placeholder: 'Ex: 30.000' },
    ],
  },
  {
    key: 'depreciation',
    name: 'Depreciação e Amortização',
    icon: TrendingDown,
    color: 'text-orange-700',
    fields: [
      { key: 'buildingsDepreciation', label: 'Depreciação de Edifícios/Estádio', placeholder: 'Ex: 200.000' },
      { key: 'equipmentDepreciation', label: 'Depreciação de Equipamentos', placeholder: 'Ex: 50.000' },
      { key: 'vehiclesDepreciation', label: 'Depreciação de Veículos', placeholder: 'Ex: 30.000' },
      { key: 'playersAmortization', label: 'Amortização de Direitos de Jogadores', placeholder: 'Ex: 2.000.000' },
      { key: 'intangibleAmortization', label: 'Amortização de Intangíveis (Marca)', placeholder: 'Ex: 100.000' },
    ],
  },
  {
    key: 'financial',
    name: 'Custos Financeiros',
    icon: Banknote,
    color: 'text-red-700',
    fields: [
      { key: 'bankFees', label: 'Taxas e Tarifas Bancárias', placeholder: 'Ex: 10.000' },
      { key: 'loanInterest', label: 'Juros de Empréstimos e Financiamentos', placeholder: 'Ex: 100.000' },
      { key: 'creditCardFees', label: 'Taxas de Cartão de Crédito', placeholder: 'Ex: 5.000' },
      { key: 'exchangeRateLoss', label: 'Perdas com Variação Cambial', placeholder: 'Ex: 20.000' },
      { key: 'investmentLoss', label: 'Perdas em Investimentos', placeholder: 'Ex: 15.000' },
      { key: 'lateFees', label: 'Multas por Atraso de Pagamento', placeholder: 'Ex: 3.000' },
    ],
  },
  {
    key: 'otherOperational',
    name: 'Outros Custos Operacionais',
    icon: Wrench,
    color: 'text-gray-700',
    fields: [
      { key: 'donationsCharity', label: 'Doações e Caridade', placeholder: 'Ex: 10.000' },
      { key: 'communityPrograms', label: 'Programas Comunitários', placeholder: 'Ex: 15.000' },
      { key: 'environmentalPrograms', label: 'Programas Ambientais', placeholder: 'Ex: 8.000' },
      { key: 'contingencyFund', label: 'Fundo de Contingência', placeholder: 'Ex: 50.000' },
      { key: 'lossOnAssetSale', label: 'Perda na Venda de Ativos', placeholder: 'Ex: 5.000' },
      { key: 'extraordinaryExpenses', label: 'Despesas Extraordinárias', placeholder: 'Ex: 20.000' },
    ],
  },
]; 